// Problem 2.
// Each new term in the Fibonacci sequence is generated by adding the previous two terms
// By starting with $1$ and $2$, the first $10$ terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.
// Solution: It is trivial fo show that F(n) is even iff n=2mod3 for n>2. We're
// going to abuse that fact extensively here.
// It is likewire straight forward to show that for the sum of all the Fibonacci numbers -3 is twice the
// sum of the even Fibonacci numbers when you sum through an even Fibonacci number. (sketch is that for n>2 the parity
// of the sequence follows the pattern o,o,e,o,o,e... then leverage the reccurance relation and follow your nose.)
// With those facts we can just sum the sequence as we generate it eliminating the need to store any intermediate terms.
// We start the generation and the running sum at index 2 so that we don't have to subtract anything later and then
// add in the 2 at the end.
package main

import "fmt"

func main() {
	var sum uint = 0
	var n1 uint = 1
	var n2 uint = 2

	for {
		if n2 > 4000000 {
			break
		}

		sum = sum + nxtFibNum(n1, n2)
		nTmp := n2
		n2 = nxtFibNum(n1, n2)
		n1 = nTmp
	}
	if n2%2 == 0 {
		sum = (sum / 2) + 2
		fmt.Println("the sum of the even Fibonacci Numbers less than or equal to 4 Milliion is: ", sum)
	}
	if n1%2 == 0 {
		sum = ((sum - n2) / 2) + 2
		fmt.Println("the sum of the even Fibonacci Numbers less than or equal to 4 Milliion is: ", sum)
	} else {
		sum = ((sum - n2 - n1) / 2) + 2
		fmt.Println("the sum of the even Fibonacci Numbers less than or equal to 4 Milliion is: ", sum)
	}
}

func nxtFibNum(n1 uint, n2 uint) uint {
	return n1 + n2
}
